Create a new library libibnetdisc
>From e1c2c10678b0d1d90f7eb31eb1c1441b5ee43311 Mon Sep 17 00:00:00 2001
From: Ira Weiny <weiny2@llnl.gov>
Date: Fri, 3 Apr 2009 15:28:08 -0700
Subject: [PATCH] Create a new library libibnetdisc

This encompasses the functionality of ibnetdiscover in a C library.  It returns
a single "ibnd_fabric_t" object which represents the data found during the
scan.  The NodeInfo, PortInfo, and SwitchInfo are preserved from the queries
made on the fabric to be used by the calling function as they see fit.

This greatly benefits some diags like iblinkinfo.pl.  This diag in particular
was re-written using this library in C and has shown an 85% speed up on a ~1000
node cluster.

Previous iblinkinfo.pl
   real    3m35.876s
   user    0m13.210s
   sys     1m1.046s

New iblinkinfotest
   real    0m32.869s
   user    0m0.067s
   sys     0m0.140s

Signed-off-by: Ira Weiny <weiny2@llnl.gov>
Signed-off-by: Sasha Khapyorsky <sashak@voltaire.com>

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -44,7 +44,7 @@ fi
 
 dnl Checks for header files.
 AC_HEADER_STDC
-AC_CHECK_HEADERS([stdlib.h string.h unistd.h fcntl.h inttypes.h netinet/in.h sys/ioctl.h syslog.h])
+AC_CHECK_HEADERS([stdlib.h string.h unistd.h fcntl.h inttypes.h netinet/in.h sys/ioctl.h])
 if test "$disable_libcheck" != "yes"
 then
 AC_CHECK_HEADER(infiniband/umad.h, [],
@@ -58,7 +58,7 @@ fi
 dnl Checks for library functions
 AC_FUNC_ERROR_AT_LINE
 AC_FUNC_VPRINTF
-AC_CHECK_FUNCS([strchr strrchr strtol strtoul memset])
+AC_CHECK_FUNCS([strchr strrchr strtol strtoul memset strtoull])
 
 dnl Checks for typedefs, structures, and compiler characteristics.
 AC_C_CONST
@@ -66,7 +66,7 @@ AC_C_CONST
 dnl Check if we should include test utilities
 AC_MSG_CHECKING(for --enable-test-utils)
 AC_ARG_ENABLE(test-utils,
-[  --enable-test-utils build additional test utilities],
+[  --enable-test-utils build additional test utilities (default=no)],
 [case "${enableval}" in
   yes) tutils=yes ;;
   no)  tutils=no ;;
@@ -136,6 +136,15 @@ IBSCRIPTPATH_TMP2="`echo $IBSCRIPTPATH_TMP1 | sed 's/^NONE/$ac_default_prefix/'`
 IBSCRIPTPATH="`eval echo $IBSCRIPTPATH_TMP2`"
 AC_SUBST(IBSCRIPTPATH)
 
+dnl Begin libibnetdisc stuff
+ibnetdisc_api_version=`grep LIBVERSION $srcdir/libibnetdisc/libibnetdisc.ver | sed 's/LIBVERSION=//'`
+if test -z $ibnetdisc_api_version; then
+   echo "FAILED to find $srcdir/libibnetdisc/libibnetdisc.ver"
+   exit 1
+fi
+AC_SUBST(ibnetdisc_api_version)
+dnl End libibnetdisc stuff
+
 AC_CONFIG_FILES([\
         Makefile \
         infiniband-diags.spec \
@@ -156,6 +165,7 @@ AC_CONFIG_FILES([\
         scripts/ibhosts \
         scripts/ibnodes \
         scripts/ibswitches \
-	scripts/ibrouters
+	scripts/ibrouters \
+   libibnetdisc/Makefile
 ])
 AC_OUTPUT
