infiniband-diags: convert documentation from nroff to rst
    Having documentation in ReStructured Text has the following benefits

    1) The addition of common functionality (options, config files, etc.) can be
       documented once and then included in documents for multiple tools.

       1a) Documentation source is more straight forward and writers can
           concentrate on the features which are unique to each tool.

    2) Documentation can be generated into multiple formats (man, html) not just
       man pages.

    3) Documentation for any individual tool is complete within that page.  (There
       is no referencing of other documents and guessing which "common" options
       apply.)

    Included as part of this patch is a complete audit of the options for these
    tools.

    Included in this initial patch are 4 tool which covered most of the options
    and the main infiniband-diags man page.

Signed-off-by: Ira Weiny <weiny2@llnl.gov>

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -167,6 +167,22 @@ fi
 AC_SUBST(ibnetdisc_api_version)
 dnl End libibnetdisc stuff
 
+dnl Generate doc/man/*.in files if possible
+DOC_DATE="`date +%Y-%m-%d`"
+AC_SUBST(BUILD_DATE)
+AC_CHECK_PROG(have_rst2man, rst2man, "yes")
+if test x$have_rst2man == xyes; then
+	doc/generate
+else
+	if test -f doc/man/infiniband-diags.8.in; then
+		echo "WARNING: 'rst2man' not found; using premade man pages"
+	else
+		echo "FAILED to find 'rst2man' required to build man pages"
+		exit 1
+	fi
+fi
+dnl
+
 AC_CONFIG_FILES([\
 	Makefile \
 	infiniband-diags.spec \
@@ -190,8 +206,11 @@ AC_CONFIG_FILES([\
 	scripts/ibrouters \
 	scripts/iblinkinfo.pl \
 	scripts/ibqueryerrors.pl \
-	man/ibqueryerrors.8 \
-	man/infiniband-diags.8 \
+	doc/man/ibaddr.8 \
+	doc/man/iblinkinfo.8 \
+	doc/man/ibnetdiscover.8 \
+	doc/man/ibqueryerrors.8 \
+	doc/man/infiniband-diags.8 \
 	libibnetdisc/Makefile \
 ])
 AC_OUTPUT
