infiniband-diags: mark duplicate/lower performing scripts as deprecated.
Inform user of alternatives if available.

Changes since V1:
	Add set_nodedesc.sh

Signed-off-by: Ira Weiny <weiny2@llnl.gov>

diff --git a/scripts/ibcheckerrs.in b/scripts/ibcheckerrs.in
--- a/scripts/ibcheckerrs.in
+++ b/scripts/ibcheckerrs.in
@@ -67,6 +67,7 @@ bw=""
 verbose=""
 brief=""
 ca_info=""
+suppress_deprecated="no"
 
 while [ "$1" ]; do
 	case $1 in
@@ -95,6 +96,9 @@ while [ "$1" ]; do
 	-s)
 		show_thresholds
 		exit 0
+		;;
+	-S)
+		suppress_deprecated="yes"
 		;;
 	-P | -C | -t | -timeout)
 		case $2 in
@@ -133,6 +137,10 @@ if [ "$portnum" = "255" ]; then
 	portname="all"
 else
 	portname=$2
+fi
+
+if [ "$suppress_deprecated" = "no" ]; then
+echo "*** WARNING ***: this command is deprecated; Please use \"ibqueryerrors\"\n\n" 1>&2
 fi
 
 if [ "$guid_addr" ]; then
diff --git a/scripts/ibdatacounts.in b/scripts/ibdatacounts.in
--- a/scripts/ibdatacounts.in
+++ b/scripts/ibdatacounts.in
@@ -34,6 +34,7 @@ bw=""
 verbose=""
 brief=""
 ca_info=""
+suppress_deprecated="no"
 
 while [ "$1" ]; do
 	case $1 in
@@ -62,6 +63,9 @@ while [ "$1" ]; do
 		fi
 		ca_info="$ca_info $1 $2"
 		shift
+		;;
+	-S)
+		suppress_deprecated="yes"
 		;;
 	-*)
 		usage
@@ -107,6 +111,10 @@ else
 fi
 
 nodename=`$IBPATH/smpquery $ca_info nodedesc $lid | sed -e "s/^Node Description:\.*\(.*\)/\1/"`
+
+if [ "$suppress_deprecated" = "no" ]; then
+echo "*** WARNING ***: this command is deprecated; Please use \"ibqueryerrors --counters\"\n\n" 1>&2
+fi
 
 text="`eval $IBPATH/perfquery $ca_info $lid $portnum`"
 rv=$?
