infiniband-diags: bash script should 'exit 255' instead of 'exit -1'
[ ~]$ sh foo.sh
+ exit -1
[ ~]$ echo $?
255

The exit status of 'exit -1' of bash script is indeed '255'.
Issues were detected by Coverity.

Signed-off-by: Honggang Li <honli@redhat.com>

diff --git a/infiniband-diags/scripts/ibdatacounts.in b/infiniband-diags/scripts/ibdatacounts.in
--- a/infiniband-diags/scripts/ibdatacounts.in
+++ b/infiniband-diags/scripts/ibdatacounts.in
@@ -6,7 +6,7 @@ usage() {
 	echo Usage: `basename $0` "[-h] [-b] [-v] [-G] [-N | -nocolor]" \
 	    "[-C ca_name] [-P ca_port] [-t(imeout) timeout_ms] <lid|guid>" \
 	    "[<port>]"
-	exit -1
+	exit 255
 }
 
 green() {
@@ -95,18 +95,18 @@ else
 fi
 
 if [ "$guid_addr" ]; then
-	if ! lid=`$IBPATH/ibaddr $ca_info -G -L $1 | awk '/failed/{exit -1} {print $3}'`; then
+	if ! lid=`$IBPATH/ibaddr $ca_info -G -L $1 | awk '/failed/{exit 255} {print $3}'`; then
 		echo -n "guid $1 address resolution: "
 		red "FAILED"
-		exit -1
+		exit 255
 	fi
 	guid=$1
 else
 	lid=$1
-	if ! temp=`$IBPATH/ibaddr $ca_info -L $1 | awk '/failed/{exit -1} {print $1}'`; then
+	if ! temp=`$IBPATH/ibaddr $ca_info -L $1 | awk '/failed/{exit 255} {print $1}'`; then
 		echo -n "lid $1 address resolution: "
 		red "FAILED"
-		exit -1
+		exit 255
 	fi
 fi
 
@@ -145,18 +145,18 @@ function blue(s)
 /ibwarn:/	{print $0}
 /iberror:/	{print $0}
 
-/^PortSelect/	{ if ($2 != '$portnum') {err = err "error: lid '$lid' port " $2 " does not match query ('$portnum')\n"; exit -1}}
+/^PortSelect/	{ if ($2 != '$portnum') {err = err "error: lid '$lid' port " $2 " does not match query ('$portnum')\n"; exit 255}}
 
 $1 ~ "(Xmt|Rcv)(Pkts|Data)" { print $1 ":........................." $2 }
 
 END {
 	if (err != "") {
 		blue(err)
-		exit -1
+		exit 255
 	}
 	if (warn != "") {
 		blue(warn)
-		exit -1
+		exit 255
 	}
 	exit 0
 }' 2>&1 && test $rv -eq 0 ; then
@@ -168,5 +168,5 @@ END {
 else
 	echo -n "Error on lid $lid ($nodename) port $portname: "
 	red FAILED
-	exit -1
+	exit 255
 fi
