ibdiags: Make escape character tack effect
[ Upstream commit bff4a96aecbddf85283a7f641eee83b1a41fb3f8 ]

The escape characters in the output of echo are often output directly
without participating in the escape. Use /usr/bin/echo to reliably get the
-e flag.

Fixes: c670c59cecbd ("infiniband-diags: mark duplicate/lower performing scripts as deprecated.")
Signed-off-by: Suwan Sun <swimlessbird@gmail.com>
Signed-off-by: Ying Lu <luying_hhu@163.com>
Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>

diff --git a/infiniband-diags/scripts/ibdatacounts.in b/infiniband-diags/scripts/ibdatacounts.in
--- a/infiniband-diags/scripts/ibdatacounts.in
+++ b/infiniband-diags/scripts/ibdatacounts.in
@@ -113,7 +113,7 @@ fi
 nodename=`$IBPATH/smpquery $ca_info nodedesc $lid | sed -e "s/^Node Description:\.*\(.*\)/\1/"`
 
 if [ "$suppress_deprecated" = "no" ]; then
-echo "*** WARNING ***: this command is deprecated; Please use \"ibqueryerrors --counters\"\n\n" 1>&2
+/usr/bin/echo -e "*** WARNING ***: this command is deprecated; Please use \"ibqueryerrors --counters\"\n\n" 1>&2
 fi
 
 text="`eval $IBPATH/perfquery $ca_info $lid $portnum`"
